[package]
name = "darts"
description = "A double array trie, A Forward Maximum Matching Searcher."
repository = "https://github.com/andelf/rust-darts"
version = "0.1.0"
license = "MIT"
authors = ["andelf <andelf@gmail.com>"]
keywords = ["trie"]

[dependencies]
rustc-serialize = "0.3"
bincode = "0.6"
log = "0.3"
clippy = "*"
