[package]
name = "darts"
description = "A double array trie, A Forward Maximum Matching Searcher."
repository = "https://github.com/andelf/rust-darts"
version = "0.1.0"
license = "MIT"
authors = ["andelf <andelf@gmail.com>"]
keywords = ["trie"]

[features]
default = []
dev = ["clippy"]

[dependencies]
bincode = "1.1"
clippy = {version = "*", optional = true}
# clippy = "*"
serde = { version = "1.0", features = ["derive"] }
